### ISSUE TITLE
OOSI: Design the Home page for click matrics

### ISSUE THREAD

**Issue by Swarnendu0123** [oxiton-foundation/click-metrics#1]
## Current:
![image](https://github.com/Websimpl-Foundation/click-metrics/assets/94161758/544c248d-c3e4-44ff-8c27-8d32fd3b1cf9)
## Expected Result:
![image](https://github.com/Websimpl-Foundation/click-metrics/assets/94161758/89283cea-28da-4601-a4a7-03d518507033)

**Comment by bhaavvya** [comment]
hi @Swarnendu0123 I would like to try this.Can you please assign it to me

**Comment by Swarnendu0123** [comment]
Go for it.

**Comment by bhaavvya** [comment]
heyy @Swarnendu0123 , I have completed the assignment
![Screenshot 2024-05-19 174030](https://github.com/oxiton-foundation/click-metrics/assets/110487270/27668e93-a7ac-4dd3-82b4-3c9ad103cc08)

**Comment by Swarnendu0123** [comment]
Thanks! please create a Pull request. Also signing into https://www.oxiton.live. You will see all of your points in the dashboard.
