### ISSUE TITLE
Build login and signup UI

### ISSUE THREAD

**Issue by Ansh101112** [oxiton-foundation/click-metrics#103]
Need to build the authentication pages UI that's login and signup page.

**Comment by anuragnegi000** [comment]
assign this issue to me :- 
as i got assigned issue #76 so i'll look for this too

**Comment by Ansh101112** [comment]
@Swarnendu0123 sir please look into this

**Comment by Swarnendu0123** [comment]
@Ansh101112 @anuragnegi000 thanks to both!

But please don't create issues without UI, if you are proposing any UI changes. Think logically, how I will be comfortable in the assignment of the issues, if UI is not front of me?

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 can I work in this issue

**Comment by Swarnendu0123** [comment]
Attach the UI.

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/oxiton-foundation/click-metrics/assets/125277258/caa2276f-d3fd-4dc6-a23c-06486559d1a4)
@Swarnendu0123

**Comment by Swarnendu0123** [comment]
This issue already exists.
