### ISSUE TITLE
Implement QR code Genearation

### ISSUE THREAD

**Issue by Rohitha-pudu** [oxiton-foundation/click-metrics#104]
I will work on generation of qr code by taking test as input .
i want to work on this issue please assign this to me

**Comment by GitSentinel** [comment]
Send the UI design once of the QR page.

**Comment by Rohitha-pudu** [comment]
> Send the UI design once of the QR page.

[https://rohitha-pudu.github.io/QRcodegenerator/](url)

**Comment by Rohitha-pudu** [comment]
![image](https://github.com/oxiton-foundation/click-metrics/assets/116823590/f3438daf-0d9f-4890-b4d3-4c1a176ed3bc)

**Comment by Swarnendu0123** [comment]
When we mean UI, we don't mean sending the UI of an existing Project. We want the UI, if you implement it how you want it to look.

**Comment by Swarnendu0123** [comment]
Closing it for now. As we have not received any updated from the issue auhor.
