### ISSUE TITLE
GSSoC: Modify the UI and the design of the analytics page.

### ISSUE THREAD

**Issue by Swarnendu0123** [oxiton-foundation/click-metrics#120]
### Description

- Add padding and margin where we need.
- the UI should look good at the final stage.

### Screenshots

![Screenshot (239)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/e6a85180-c530-41c5-8b9e-1b8a91f94545)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

- 3 days.

**Comment by Prime351585** [comment]
Sure I'll finish it by this evening assign it to me

**Comment by Swarnendu0123** [comment]
Assigned to you. Also, take care of the profile dropdown in the analytics page.
