### ISSUE TITLE
[Feature] GSSoC : Themes page from Link-in-bio page

### ISSUE THREAD

**Issue by lazybug19** [oxiton-foundation/click-metrics#125]
# Feature to issue #5

### Description
![m](https://github.com/oxiton-foundation/click-metrics/assets/105040967/62a8650b-627e-4f63-b4ff-317e5309c348)

- Upon clicking view more themes in the end, user should be redirected to themes page.
- This page wouldn't be included in side-bar but will remain as a redirected page like the help page.

### Changes You need to make

Changes in following files

- /src/components/pages/Theme.tsx
- /src/assets/icons.tsx

### Checklist

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Design

-  Carousel type theme cards which can be user customizable too
-  Tech Stack: React, Vite, TailwindCSS, TypeScript, NextUI/RadixUI libraries for enhanced UI
-  Story user info for chosen them-cards using MongoDB

**Comment by Swarnendu0123** [comment]
Follow the issue template. You have not followed the issue template.

**Comment by Swarnendu0123** [comment]
You shouldn't mention anyone in the issue's description.

**Comment by lazybug19** [comment]
@Swarnendu0123 Made changes and updated.
