### ISSUE TITLE
Corrections in contributing.md file - Gssoc24

### ISSUE THREAD

**Issue by PradnyaGaitonde** [oxiton-foundation/click-metrics#126]
### Description

Describe the purpose and scope of your pull request here. Include a brief overview of the changes introduced and any relevant context that reviewers should be aware of.
There are a few corrections to be made in the contributing file. Could you please assign me this issue under gssoc24.

### Changes You need to make

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your modifications.

- file1
- file2
- file3

### Screenshots

Attach screenshots or Videos demonstrating the visual changes introduced by your pull request. This helps reviewers understand the user interface modifications more effectively.

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

Provide an estimate of the time required to complete the changes proposed in this issue. This could be a rough estimate or a specific timeframe based on your availability and the complexity of the task.
In a few hours of being assigned.
### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Swarnendu0123** [comment]
Please don't create irrelevant issues. You just created the issue with the template itself. Didn't describe anything.
