### ISSUE TITLE
Create a Loader for the Website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [oxiton-foundation/click-metrics#130]
### Description
Create a Loader for the Website,when user enter to the website

https://github.com/oxiton-foundation/click-metrics/assets/125277258/8073907d-f322-43e8-9a41-3b2c656c979d

(attach the older screenshot here)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

1 day or less

**Comment by Swarnendu0123** [comment]
Please attach the screenshot on the description!

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 here are some best loaders for your website
https://github.com/oxiton-foundation/click-metrics/assets/125277258/bb82b844-b635-40d0-8bcb-5c5aff99f44e


https://github.com/oxiton-foundation/click-metrics/assets/125277258/861c9502-1609-4fd1-b940-5cb92b5cdecf

**Comment by Swarnendu0123** [comment]
For me the first one is fine.

**Comment by Swarnendu0123** [comment]
Closing it for now.
