### ISSUE TITLE
 GSSoC:  Sidebar mobile Responsiveness issue

### ISSUE THREAD

**Issue by anisharma07** [oxiton-foundation/click-metrics#134]
### Description

The Sidebar is moving with the body of website in mobile devices, It should be floating over the body for mobile responsive.

### Changes You need to make

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your modifications.

- update the tailwind.css code and use media queiries to make sidebar float for mobile device
- use of useState hooke to keep the track of state of sidebar
- all changes to be done in sidebar and header component only

### Screenshots

https://github.com/oxiton-foundation/click-metrics/assets/126901961/538a66a6-5505-4398-954f-44333e888b27

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

If Assigned today, will complete it by tomorrow

**Comment by Swarnendu0123** [comment]
Assigned to you:)
