### ISSUE TITLE
GSSoC: Implement dynamic qr code generation

### ISSUE THREAD

**Issue by Swarnendu0123** [oxiton-foundation/click-metrics#138]
### Description

Implement dynamic QR code generation. Currently the QR code is static, make a input box where user can give input of an URL and generate the QR code dynamically.

**Comment by nishant0708** [comment]
Can i work on this Issue??

**Comment by GOKULGSECE** [comment]
As i have implemented this Qrcode generator before i have a experience of creating and also downloading this Qr generated dynamically please assign me this under Gssoc'24

**Comment by Swarnendu0123** [comment]
Assigned to yiu @GOKULGSECE
