### ISSUE TITLE
GSSoC: Duplicate declarations of the variables header.tsx

### ISSUE THREAD

**Issue by arpy8** [oxiton-foundation/click-metrics#141]
### Description

Duplicate declarations of the variables `dropDownIsActive` and `setDropdownIsActive` in `header.tsx`

### Changes You need to make

remove duplicate declarations in the header.tsx file

### Screenshots

![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/76db9c19-221e-48a0-a89b-8fb067556f5e)

![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/faed1b13-2b40-4957-a568-46da6ba6a8d8)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

≈ a minute 🗣️🔥

**Comment by arpy8** [comment]
@Swarnendu0123 can you please assign gssoc label to it? thanks

**Comment by Swarnendu0123** [comment]
Thanks! assigned level to it.
