### ISSUE TITLE
GSSOC: Bug: The Enter URL text area is has black bg in links

### ISSUE THREAD

**Issue by arpy8** [oxiton-foundation/click-metrics#144]
### Description

The text area in the links section has black background making the text difficult to read while being typed.

### Changes You need to make

Add  `bg-white` class in the input tag to make background white.

Files needed to be modified:
- `links.tsx`

### Screenshots

Before:
![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/f2018599-d25f-479e-94fd-0e9298e6a1aa)

After:
![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/223c4289-d977-4631-af4e-c9a1f2152a37)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

30 seconds

**Comment by arpy8** [comment]
hi @Swarnendu0123, could you please add gssoc tags to this issue

**Comment by Swarnendu0123** [comment]
This is just an issue right? Are there any scores for issues also?
