### ISSUE TITLE
Feat: Adding Campaign Page

### ISSUE THREAD

**Issue by arpy8** [oxiton-foundation/click-metrics#147]
### Description

Currently the website is missing the campaign page. I would like to work on it.

### Changes You need to make

- `campaign.tsx`
- `app.tsx`

### Screenshots

Before:
![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/5ec65151-c99c-4d40-a9d9-0fe19e411adf)

After:
![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/a944bc3e-751d-4c06-9dc0-f6122efa98bc)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

2 days

**Comment by Swarnendu0123** [comment]
I guess there is already an issue that exists, which points towards the same problem. Find out that and continue over there.

**Comment by Swarnendu0123** [comment]
You can go with this! As other contributors who have raised those issue, are inactive.
