### ISSUE TITLE
GSSoC: Shorten URL card is too small in mobile screen 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [oxiton-foundation/click-metrics#148]
### Description

Bug;Shorten URL card is too small in mobile screen , we can make it little bit big and which is good to see..

### Changes You need to make

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your notification 

### Screenshots
![Screenshot_2024-06-07-23-39-28-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/oxiton-foundation/click-metrics/assets/125277258/8da83c35-4827-4c32-90a5-d805e81fd467)
Attach screenshots or Videos demonstrating the visual changes introduced by your pull request. This helps reviewers understand the user interface modifications more effectively.

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [ ] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [ ] Attached OSSI or GSSoC in the heading of the Issue.
- [ ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete
  In between 1 day

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Swarnendu0123** [comment]
Assigned to you @RamakrushnaBiswal
