### ISSUE TITLE
GSSoC: Change the default vite icon

### ISSUE THREAD

**Issue by sweta-singh28** [oxiton-foundation/click-metrics#15]
Replace the default Vite icon with a customized logo. Please assign it to me.

**Comment by Swarnendu0123** [comment]
Go ahead!

**Comment by sweta-singh28** [comment]
> Are you going to design the logo for click matrics?
> @sweta-singh28 

Yes

**Comment by Swarnendu0123** [comment]
Okay, Raise a PR by `30th May`
