### ISSUE TITLE
GSSoC: Make sidebar hidden when click on any sidebar links

### ISSUE THREAD

**Issue by krishna-singha** [oxiton-foundation/click-metrics#152]
- We need to enhance the user experience by implementing functionality that hides the sidebar whenever a link within the sidebar is clicked. This will allow the main content to take full focus.
- Before claiming this issue go through #24 
- Discuss your approach here; if it's acceptable, we will assign you this issue.

**Comment by anisharma07** [comment]
APPROACH ONE:
Sliding for Mobile only:
Fix the sidebar at width > 1024 (optimum for viewing the main page with sidebar open) and make it sliding menu for mobile.

APPROACH TWO:
sliding for both mobile and desktop
At screens > 1024 (desktop screens) : IT will manually slide
For MOBILE or width<1024 : Will be closed by Default; IT will close when link is clicked

ALSO: i'm thinking of adding a overlay to mobile version of sidebar that will look like below ss:
![Screenshot 2024-06-08 193834](https://github.com/oxiton-foundation/click-metrics/assets/126901961/c16c1875-c460-4a9b-baf2-e2649c99ef1e)



It will help to close sidebar easily


It will fix all major bugs related to sidebar... in one PR ...

If you like any of the approach ... let me know and assign this issue to me
please consider levelling up the ISSUE if you want all these changes done in a single PR...

**Comment by krishna-singha** [comment]
- Ok your approach two was cool. You can continue with that and also add overlay for mobile version.
- Before that go through #24.
- I am assigning this issue to you.
- Best of luck.

**Comment by krishna-singha** [comment]
- And also add NavLink in the Create New button as it refreshing the page when clicked on it.

**Comment by anisharma07** [comment]
> * Ok your approach two was cool. You can continue with that and also add overlay for mobile version.
> * Before that go through [Rules to contribute at Girl Script Summer of Code 2024(GSSoC) and Oxiton Open Source Internship 2024(OOSI) #24](https://github.com/oxiton-foundation/click-metrics/issues/24).
> * I am assigning this issue to you.
> * Best of luck.

Yeah! gone through these already

**Comment by krishna-singha** [comment]
> > * Ok your approach two was cool. You can continue with that and also add overlay for mobile version.
> > * Before that go through [Rules to contribute at Girl Script Summer of Code 2024(GSSoC) and Oxiton Open Source Internship 2024(OOSI) #24](https://github.com/oxiton-foundation/click-metrics/issues/24).
> > * I am assigning this issue to you.
> > * Best of luck.
> 
> Yeah! gone through these already

OK fine.

**Comment by anisharma07** [comment]
> * And also add NavLink in the Create New button as it refreshing the page when clicked on it.

what to do with the create new button.... Where is the navlink,.. can you please elaborate...

**Comment by krishna-singha** [comment]
<img width="466" alt="Screenshot 2024-06-08 at 8 22 59 PM" src="https://github.com/oxiton-foundation/click-metrics/assets/128041532/6e62e30e-d091-4814-b1a8-63dff35db8da">

Instead of anchor tag use NavLink from React-router-dom which is already imported in the top.

**Comment by anisharma07** [comment]
> * from

ok got it..will crrect it
