### ISSUE TITLE
GSSoC : Scroll to top + Dark/Default Toggler

### ISSUE THREAD

**Issue by Vipullakum007** [oxiton-foundation/click-metrics#157]
### Description

Add  Scroll to top + Dark/Default Toggler

### Changes You need to make

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your modifications.

- file1
- file2
- file3

### Screenshots

Attach screenshots or Videos demonstrating the visual changes introduced by your pull request. This helps reviewers understand the user interface modifications more effectively.

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [ ] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [ ] Attached OSSI or GSSoC in the heading of the Issue.
- [ ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

Provide an estimate of the time required to complete the changes proposed in this issue. This could be a rough estimate or a specific timeframe based on your availability and the complexity of the task.

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Vipullakum007** [comment]
hey @krishna-singha , please assign me i want to work on it.

**Comment by Swarnendu0123** [comment]
We don't need this as the move to the top is not needed for now. And the dark/light theme issue already exists. You should check if it already exists or not issues before creating an issue.
