### ISSUE TITLE
About us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [oxiton-foundation/click-metrics#165]
### Description
I will create an about us page for the website so that user can get the abstract view of the website 

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [ ] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [ ] Attached OSSI or GSSoC in the heading of the Issue.
- [ ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

1 Day

**Comment by Swarnendu0123** [comment]
We don't need this for now!
