### ISSUE TITLE
Enhance Navbar.

### ISSUE THREAD

**Issue by naisargi17** [oxiton-foundation/click-metrics#166]
The search bar should be in middle and  the upgrade button ui is not proper.

**Comment by Swarnendu0123** [comment]
What do you mean by `not proper`. Be specific, attach screenshots.

**Comment by naisargi17** [comment]
In upgrade button the top padding is more and this button can be style as round and the padding between the content and border must have some space.
For example just look at the comment button

![btn](https://github.com/oxiton-foundation/click-metrics/assets/111778403/9f35d68d-5ea7-49a1-b14f-e752d6c49e3f)

**Comment by Swarnendu0123** [comment]
We don't need the changes you proposed. Thanks!
