### ISSUE TITLE
GSSOC: Feat: Add frontend for custom link

### ISSUE THREAD

**Issue by arpy8** [oxiton-foundation/click-metrics#169]
### Description

I wish to design the frontend for custom link button

### Changes You need to make

- `[custom-links.tsx](https://github.com/oxiton-foundation/click-metrics/blob/main/client/src/components/pages/custom-links.tsx)`

### Screenshots

Before:
![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/9416dc99-fbdf-47ef-8c55-bfe27187809b)

After:
![image](https://github.com/oxiton-foundation/click-metrics/assets/74809468/b7405e2f-fefd-4bc0-9d76-87c28ba26d12)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

Provide an estimate of the time required to complete the changes proposed in this issue. This could be a rough estimate or a specific timeframe based on your availability and the complexity of the task.

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Swarnendu0123** [comment]
Good! Go for it.
