### ISSUE TITLE
GSSoC:Shorten url button throws an error

### ISSUE THREAD

**Issue by Stiffpixels** [oxiton-foundation/click-metrics#170]
### Description

shorten url button does not work as axios is not able to make a request.

### Changes You need to make
I will have to work on the issue to find out the files .

### Screenshots

https://github.com/oxiton-foundation/click-metrics/assets/32983571/de6bc5ee-a533-4b91-8b27-1a65efd3d7d0

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [ ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

2 days after assignment.

### Additional Notes

please assign me this issue under gssoc24'

**Comment by Swarnendu0123** [comment]
We haven't deployed the backend yet. The axios is already available as you have installed all the dependencies. We will eventually implement the backend. Thanks. Closing it for now.
