### ISSUE TITLE
GSSoC: QR Code page UI and Customizations

### ISSUE THREAD

**Issue by anisharma07** [oxiton-foundation/click-metrics#171]
### Description

I would like to code the UI for QR code page and add customizations to the generate qr code feature.

### Changes You need to make

Will add feature to change:
1. color
2. size
3. margin
4. format
etc.. for the qr code to be generated ....

Files to be changed: 
- client\src\components\pages\qr-codes.tsx
- building new components

I have gone through the qr code api to check for parameters that I can add to the qr code...

Checkout the UI design I have built on figma for the QR code page... any further improvements are open for changes...

### Screenshots

![image](https://github.com/oxiton-foundation/click-metrics/assets/126901961/7f70f04e-5e21-4ba4-9ac9-7cd28748da95)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

around 2-4 days

### Additional Notes

I will make the page mobile responsive as well and add most api features to customize the QR Code based on user needs....
I will also add a loading animation on qr code image when generate qr is clicked to provide a feedback to the user.

If you like the changes, please assign the Issue to me and add gssoc labels and appropriate level....

**Comment by anisharma07** [comment]
> Have youi gone through the Current page ? @anisharma07
> 
> It looks like ![image](https://private-user-images.githubusercontent.com/100017129/339072900-af0d035c-d496-4500-bd91-3ff75cd05236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTM5NzksIm5iZiI6MTcxODIxMzY3OSwicGF0aCI6Ii8xMDAwMTcxMjkvMzM5MDcyOTAwLWFmMGQwMzVjLWQ0OTYtNDUwMC1iZDkxLTNmZjc1Y2QwNTIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNzM0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjllMGI4YzQ5YzFjZTA2ZjBjYjVlODM2M2YzMTkyYzYyOWFlNzQ2MGQ2ZTI5OTNiYzhkMmQ2MjljZmRlODExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vi1E6TDhGoYVK7C0Lq32f3FvBl6eI_mMJhcsGCSV4CU)

yeah I know ...

**Comment by Smitkhobragade** [comment]
Okay. Then I am assigning this to you...
