### ISSUE TITLE
GSSoC : SEARCH Not functional on Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [oxiton-foundation/click-metrics#172]
### Description

The search bar is not functional on mobile screen. It got overlapped by the menu icon

![image](https://github.com/oxiton-foundation/click-metrics/assets/124615886/366a2532-eb0e-43ff-9ca9-fe3742fa7495)

### Changes You need to make
I will implement a search bar to expand on clicking on search icon else stay in the small area.

- file1
- file2
- file3

### Screenshots

Attach screenshots or Videos demonstrating the visual changes introduced by your pull request. This helps reviewers understand the user interface modifications more effectively.

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

1 Day

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Utsavladia** [comment]
I would love to contribute to this project. Please assign this to me to enhance the user experience.

**Comment by Smitkhobragade** [comment]
@Utsavladia . can you attach a rough sketch like how it will look ? Also how are you going to solve it.?

**Comment by Smitkhobragade** [comment]
> @Smitkhobragade  sure, 
> something like this ...
> ![image](https://github.com/oxiton-foundation/click-metrics/assets/124615886/2bd94178-15fe-4acf-9309-6c89c89668d8)
> 

Okay. Just a small change try to add the search icon overlayed on search bar only. Rest is fine. And if space remains try to have one button at right corner...

**Comment by Smitkhobragade** [comment]
You can go for it. I am assigning you this issue.
