### ISSUE TITLE
GSSoC : Link the options on hero section to the respective pages

### ISSUE THREAD

**Issue by Utsavladia** [oxiton-foundation/click-metrics#173]
### Description

The options given in the hero section should be clickable and link to the respective page.

### Changes You need to make

I will direct the links to the respective pages.

- file1
- file2
- file3

### Screenshots
![image](https://github.com/oxiton-foundation/click-metrics/assets/124615886/db92ff8e-62e0-4cd3-95a8-b8530798736d)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

1 day
### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Swarnendu0123** [comment]
I also felt the same! Go ahead.
