### ISSUE TITLE
GSSoC: Create a plans page for showing pricing options

### ISSUE THREAD

**Issue by MadhurimaNayak** [oxiton-foundation/click-metrics#174]
### Description

Clicking on the 'view our plans' button in the campaigns section currently does not redirect to anything. I will make a page that will showcase the premium plan with different pricing options (according to length of plan selected) + the different features that would be available to user.

### Changes You need to make

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your modifications.

- file1
- file2
- file3

### Screenshots

![image](https://github.com/oxiton-foundation/click-metrics/assets/124715194/2e2e765e-83f6-450c-a45f-460749388faa)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

Around 1 to 2 days after assignment of issue.

### Additional Notes

After this page is made, and the user clicks on button to opt in for a particular plan, a login window should pop up if they have not logged in already. If they have, then they should be redirected to the payment portal.

**Comment by Swarnendu0123** [comment]
Our target is to serve it for free. We don't need this!

**Comment by MadhurimaNayak** [comment]
@Swarnendu0123 okay, could I ask what is the purpose of having this page then?
