### ISSUE TITLE
[STYLE] GSSoc'24 adding transitions to the options in hero section

### ISSUE THREAD

**Issue by Anshika-Gochar** [oxiton-foundation/click-metrics#178]
### Description
The options given in the hero section should be having transition or transforms on clicking the below screenshots will explain it will make it more appealing and attractive.

### Changes You need to make
we need to make changes in the files

- file1
- file2
- file3

### Screenshots

![oxytonissue2](https://github.com/oxiton-foundation/click-metrics/assets/148606019/fd157830-bc56-40b1-96d2-9f12cdde01ad)
 
now we can add transform or transitions like given below :
![oxytonissue](https://github.com/oxiton-foundation/click-metrics/assets/148606019/c05f1145-10c3-4566-b45a-a6f2268640bf)
this is just the example for style change .

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [ YES] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [YES ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [ YES] Attached OSSI or GSSoC in the heading of the Issue.
- [YES ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete
1 day would be more than sufficient to do this work

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

**Comment by Anshika-Gochar** [comment]
Please assign this issue to me under GSSoc'24

**Comment by Swarnendu0123** [comment]
Thanks but we don't want this type of design. We want minimal design.
