### ISSUE TITLE
GSSoC: Setting up a login and signup system

### ISSUE THREAD

**Issue by StephenStolk** [oxiton-foundation/click-metrics#18]
- There is no backend system for login and signup. The users can create their own account and keep track of all their works they have assessed till now.
- A Landing page demonstrating the services offered and a route to login/signup before commencing on utilizing the products.

Tech stack: Express, Mongodb, bcrypt, Tailwind

![image](https://github.com/oxiton-foundation/click-metrics/assets/134587780/1e515624-7589-407a-96a9-e501f1c1b782)

I want to grab up this issue, if approved

**Comment by StephenStolk** [comment]
I am interested in taking up this issue.

**Comment by Swarnendu0123** [comment]
Hello @StephenStolk, thanks for raising this issue. I want you to create two separate PRs. 
1. For the Landing Page
2. For the Signup page. Use Firebase for authentication. Don't push the Firebase config in this. We will configure the configs. Don't change any files in the Backend.
Thanks!

**Comment by Swarnendu0123** [comment]
## The landing page should have these Sections:
![Screenshot (226)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/5319dea3-01dc-4f13-b900-745dfd59e90b)
![Screenshot (227)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/02e7bd50-1ab2-44f1-82cc-534310f3e288)
![Screenshot (228)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/a0512b0d-479e-433a-a4ef-413332edf611)
![Screenshot (229)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/d4faa492-7f1c-4c80-9454-f0cd4eaa8f1a)
![Screenshot (230)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/2638cb80-b04b-49e1-b2b6-15913775fb18)

**Comment by StephenStolk** [comment]
Alright. I will pull up the design after building it up.

**Comment by Swarnendu0123** [comment]
Signup to https://www.oxiton.live/
and follow https://github.com/oxiton-foundation
