### ISSUE TITLE
Gssoc: remove all the component files other than `shadcn ui` and implement `shadcn ui`

### ISSUE THREAD

**Issue by Swarnendu0123** [oxiton-foundation/click-metrics#180]
### Description

Remove all the component files other than `shadcn ui` and implement `shadcn ui`. 
Ref: https://ui.shadcn.com/

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [ ] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [ ] Attached OSSI or GSSoC in the heading of the Issue.
- [ ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

1 week

**Comment by Asymtode712** [comment]
@Swarnendu0123 I would like to work on this issue, would you please assign me to it

**Comment by Swarnendu0123** [comment]
Assigned to you!

**Comment by Asymtode712** [comment]
Hey @Swarnendu0123 , I had a doubt: currently our website is using the button component from the `ui` folder of `client/src` directory so do we have to replace it too with the `shadcn` component of Button

**Comment by Swarnendu0123** [comment]
> Hey @Swarnendu0123 , I had a doubt: currently our website is using the button component from the `ui` folder of `client/src` directory so do we have to replace all its instances with the `shadcn` component of Button

To be very genuine, I don't use UI lib very frequently. But @rahulpoonia29 can definitely suggest how you can implement it.

**Comment by Asymtode712** [comment]
> Hey @Swarnendu0123 , I had a doubt: currently our website is using the button component from the `ui` folder of `client/src` directory so do we have to replace all its instances with the `shadcn` component of Button

@rahulpoonia29 need your help here!

**Comment by rahulpoonia29** [comment]
@Asymtode712 The UI folder contains the ShadCn components.

**Comment by rahulpoonia29** [comment]
@Asymtode712 The loader and search component are not from ShadCn. Move them to their respective folders in components if they are pure react components without any dependencies.

**Comment by Asymtode712** [comment]
@rahulpoonia29 ok got it
