### ISSUE TITLE
[Feat]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [oxiton-foundation/click-metrics#185]
#### Currently, there is no issue template for this repo and no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/apu52/METAVERSE/assets/73957207/4c6889aa-3abf-485d-9c41-09f1f562a0aa)

- and issue templates:

![image](https://github.com/apu52/METAVERSE/assets/73957207/6827e4a8-5382-4376-bbf6-afb9f9731252)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete
- 1 day

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by Swarnendu0123** [comment]
You can start working @TonyStark-47

**Comment by TonyStark-47** [comment]
Hey @Swarnendu0123, I have raised a PR #190 related to this issue. Please check it out.
