### ISSUE TITLE
[GSsoc] fix:Contact us Page not showing

### ISSUE THREAD

**Issue by ManpreetSingh18** [oxiton-foundation/click-metrics#186]
### Description

Only Contact Us is showing on the help page.No form is there.I will add things like below

### Changes You need to make

Add form Code in the Help Page

### Screenshots

BEFORE

![Screenshot 2024-06-20 134949](https://github.com/oxiton-foundation/click-metrics/assets/72294811/3fd2eb95-5e22-494b-bcd9-ce66754a485e)

AFTER  

![Screenshot 2024-06-20 134911](https://github.com/oxiton-foundation/click-metrics/assets/72294811/58e2d851-60b3-4067-aedd-f24381576c5f)

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [ ✔] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [ ✔] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [ ✔] Attached OSSI or GSSoC in the heading of the Issue.
- [✔ ] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

I can complete It today itself

**Comment by Swarnendu0123** [comment]
We Don't need this UI. Previously you worked on it but your work was very unstructured. We want to continue with shadcn UI.
