### ISSUE TITLE
GSSoC: Design the profile dropdown.

### ISSUE THREAD

**Issue by Swarnendu0123** [oxiton-foundation/click-metrics#19]
# Currently, we don't have any profile dropdown. Design the profile dropdown.
![Screenshot (231)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/2ccaa71a-9449-4b39-90eb-3ec1cdc0c76d)

## Prerequisites:
1. Signup to https://www.oxiton.live/
2. Follow https://github.com/oxiton-foundation

**Comment by tom-blk** [comment]
Is it okay if I contribute on this?

**Comment by Swarnendu0123** [comment]
> Is it okay if I contribute to this?

I just need the UI which you are going to develop. Present the UI and I will assign this issue to you.

**Comment by tom-blk** [comment]
> I just need the UI which you are going to develop. Present the UI and I will assign this issue to you.

Can I just code it out and do a PR?

**Comment by Swarnendu0123** [comment]
Before that, I need to verify the design.
