### ISSUE TITLE
💡[Feature]: Adding customizable QR code style

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [oxiton-foundation/click-metrics#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

we can add logo center of the qr like the below img

### Use Case

new stylish QR

### Add ScreenShots

![image](https://github.com/oxiton-foundation/click-metrics/assets/125277258/42bbf299-05d7-4fca-98cb-706f7595a223)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 can i work upon it

**Comment by Swarnendu0123** [comment]
yes!

**Comment by Swarnendu0123** [comment]
login to oxiton.live

**Comment by RamakrushnaBiswal** [comment]
Logged in

**Comment by Swarnendu0123** [comment]
Assigned to you!
