### ISSUE TITLE
OOSI: Design the Analytics page for click matrics

### ISSUE THREAD

**Issue by krishna-singha** [oxiton-foundation/click-metrics#2]
# Current:

<img width="1710" alt="Screenshot 2024-05-13 at 11 30 06 PM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/ef68c258-77f0-4c20-8fe4-d897b2053295">

<br>

# Expected Result:

<img width="1710" alt="Screenshot 2024-05-13 at 11 31 24 PM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/5b3d206a-1be7-42b0-b029-3ad012b78520">
<img width="1710" alt="Screenshot 2024-05-13 at 11 31 45 PM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/1186aaec-7248-44aa-85d8-f4c2774500de">

**Comment by juniperus01** [comment]
Hi @Swarnendu0123 I would like to work on this issue as a part of gssoc contributor. Also, can you add gssoc label to this?

**Comment by dhruv8433** [comment]
@Swarnendu0123

i would like to work on that issue 
can you please assign it to me

**Comment by Swarnendu0123** [comment]
This issue is already taken, claim a new one!

**Comment by Swarnendu0123** [comment]
@Prime351585 are you working on it? Otherwise we have to reassign!

**Comment by Prime351585** [comment]
Wait you already merged the PR #86 for this issue I already have made the page,with date filter as well and a JSON file to keep track of the cities and dates, if you want anything else for the same let me know.

**Comment by Swarnendu0123** [comment]
Oh Sorry! I have not seen that. Thanks though!

**Comment by Prime351585** [comment]
No problem, it was a good experience making dashboards, I learned a lot.

**Comment by Swarnendu0123** [comment]
> No problem, it was a good experience making dashboards, I learned a lot.

Go for https://github.com/oxiton-foundation/click-metrics/issues/120

**Comment by Prime351585** [comment]
And I also want to know about what type of modules are we intending to implement in that add modules button..?
