### ISSUE TITLE
📝[Docs]: Add FAQ section

### ISSUE THREAD

**Issue by ananyag309** [oxiton-foundation/click-metrics#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Addition of frequently asked question i.e. faq section will be highly beneficial for the project. As the website doesn't have a contact us page rn so it will be best to add it so that user might have a clearance of their doubt through it. I am willing to work on this issue under gssoc.  

### Suggested Change

I will add FAQ section below custom link
![faq](https://github.com/oxiton-foundation/click-metrics/assets/145869907/571cf28b-3441-422f-9069-edb567d2518b)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Swarnendu0123** [comment]
We don't need this section for now.
