### ISSUE TITLE
📝[Docs]: Enhance readme.md

### ISSUE THREAD

**Issue by ananyag309** [oxiton-foundation/click-metrics#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I am willing to enhance readme.md under gssoc. It will be great if we add a section called feature in - where we can feature the project was part of gssoc. i am adding a sample pic to realte with it. not only this i will change style and add some more parts to it making it more atracted and presentable

### Suggested Change

i made this, 
![read](https://github.com/oxiton-foundation/click-metrics/assets/145869907/895557dd-0495-4f12-ab00-59991914dbf1)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Smitkhobragade** [comment]
@Swarnendu0123 . please look into this issue.

**Comment by Swarnendu0123** [comment]
When it comes to Readme files we generally give descriptions of the software/product. We don't write about the events we are participating in. GSSoC is just an event of 3 months, it shouldn't be there in the readme. We already have a detailed description about how to participate in GSSoC in #24.
