### ISSUE TITLE
🐞[Bug]: Fixed Size Qr code Display & animated sidebar

### ISSUE THREAD

**Issue by anisharma07** [oxiton-foundation/click-metrics#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

QR code
--> when size of QR code is set high .. its size on the page becomes too large causing problem

Sidebar
--> adding slide animation when opening closing sidebar would look good rather than just hide and unhide instantly

### Expected behavior

--> QR code display size should be fixed to some particular width height & only resolution will be updated on size increase that will be seen when image is downloaded..
--> QR code size limit should be added rather than choosing any random size.

--> Sidebar should appear sliding towards right and close towards left with animation..

### Add ScreenShots

![WhatsApp Image 2024-07-17 at 18 09 14_2116d256](https://github.com/user-attachments/assets/25c856b6-ed40-400f-bbbe-b8f892b43f7a)
![image](https://github.com/user-attachments/assets/ff09be2b-8e8a-47fe-8708-923d335f9da7)

https://github.com/user-attachments/assets/3abf9de2-aed7-473c-b92d-020a6a9c0cd2

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Smitkhobragade** [comment]
SO you want to work on it @anisharma07 ?

**Comment by anisharma07** [comment]
yes @Smitkhobragade

**Comment by Smitkhobragade** [comment]
> yes @Smitkhobragade 

Okay you can start working on it. I'll assign it to you.
