### ISSUE TITLE
💡[Feature]:  Loading gif on Generate & Organizing Download Buttons

### ISSUE THREAD

**Issue by anisharma07** [oxiton-foundation/click-metrics#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

-> A loading gif will appear when User clicks on Generate QR code Button
-> The gif will disappear when the QR code is generated and original QR will be displayed.
-> The download buttons will be organised by putting different formats into a dropdown which will allow to choose type of formats to download OR I can Create icons like the ones added in  the screen shot & add additional Print Button.

++ I'm also thinking to add a dummy disabled qr code to space where QR will be generated like the screenshot below to provide feedback to user that where their QR will be after generation.. 

### Use Case

--> User will get a feedback untill the Qr is generated.

### Benefits

--> layout will become compact with lesser number of download elements

### Add ScreenShots
![image](https://github.com/user-attachments/assets/b126d6eb-546e-412e-a2ca-b573431b4fc8)
![image](https://github.com/user-attachments/assets/f4ca65ee-4b7f-440e-b9bd-a33e1e748295)

![image](https://github.com/user-attachments/assets/03c67dba-347a-42f2-96f2-503542f31e4a)

Please Assign Under GSSo'C 24

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Smitkhobragade** [comment]
@anisharma07 can you share how the GIF will look like ? rest your idea sounds interesting.

**Comment by anisharma07** [comment]
> @anisharma07 can you share how the GIF will look like ? rest your idea sounds interesting.

A simple loader like this to provide feedback to the user during qr generation process through api
https://github.com/user-attachments/assets/18ad3a2f-4545-4aed-8b3e-7602be4dfa67

**Comment by Smitkhobragade** [comment]
Okay @anisharma07 Start working i'll assign it to u.

**Comment by anisharma07** [comment]
@Smitkhobragade 

Here are some of the loaders I find good... tell me which one to apply...
https://github.com/user-attachments/assets/50fb93ea-8f64-4eea-aa41-783d578d776f
