### ISSUE TITLE
GSSoC: change the logo in the sidebar

### ISSUE THREAD

**Issue by abhay-sen** [oxiton-foundation/click-metrics#21]
## Issue: change the logo in the sidebar of your project with the new logo present in the icon
![Screenshot 2024-05-27 155041](https://github.com/oxiton-foundation/click-metrics/assets/144714595/8e4b6190-37ad-4efc-8a5d-4290cf185619)
## Prerequisites:
Signup to https://www.oxiton.live/
Follow: https://github.com/oxiton-foundation
Follow: https://www.linkedin.com/company/oxiton-foundation
Follow: https://www.instagram.com/oxitonfoundation/
Join us: https://discord.gg/DVWNcTqD
Follow: https://www.facebook.com/people/Oxiton-Foundation/61559802086402/
Follow: https://dev.to/oxiton_foundation

**Comment by Swarnendu0123** [comment]
Hello @abhay-sen fulfill the prerequisits

## Prerequisites:
Signup to https://www.oxiton.live/
Follow: https://github.com/oxiton-foundation
Follow: https://www.linkedin.com/company/oxiton-foundation
Follow: https://www.instagram.com/oxitonfoundation/
Join us: https://discord.gg/DVWNcTqD
Follow: https://www.facebook.com/people/Oxiton-Foundation/61559802086402/
Follow: https://dev.to/oxiton_foundation

**Comment by abhay-sen** [comment]
Okay sir

**Comment by abhay-sen** [comment]
DONE 
just left facebook as i dont have an account there

**Comment by Swarnendu0123** [comment]
Assigned the issue to you. Read the rules before proceeding: https://github.com/oxiton-foundation/click-metrics/issues/24
