### ISSUE TITLE
🐞[Bug]: Found some bugs related to QR code page & sidebaar

### ISSUE THREAD

**Issue by anisharma07** [oxiton-foundation/click-metrics#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

--> There is closing transition in sidebar when loaded in mobile view.
--> The click metrics logo can be fixed so resizing of sidebar do not occur
--> The path of qr code logo need to be fixed too.

### Expected behavior

--> These bugs need to be fixed

### Add ScreenShots

![image](https://github.com/user-attachments/assets/669b5a35-5edc-46e8-ab2a-89b491c8628c)

https://github.com/user-attachments/assets/1865468a-2911-4768-a68b-469cec2b3616

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Smitkhobragade** [comment]
What is the problem @anisharma07 . Its actually  working fine.
[iPhone-12-PRO-click-metrics.vercel.app-T0taKcPOUK.webm](https://github.com/user-attachments/assets/8d2ce9b7-67fc-4b7d-b7aa-18cd218c4135)

**Comment by anisharma07** [comment]
@Smitkhobragade 

Actually when you load the website .. the sidebar is intially open and it closes instantly with a transition which should not happen....
sidebaar should be closed by default when it is opened in mobile window... watch the video carefully



https://github.com/user-attachments/assets/1865468a-2911-4768-a68b-469cec2b3616

**Comment by Smitkhobragade** [comment]
Okay. You can start working on it I'll assign it to u.
