### ISSUE TITLE
GSSoC: Readme.md update required 

### ISSUE THREAD

**Issue by Meetjain1** [oxiton-foundation/click-metrics#28]
Currently Our readme.md file is not looking good 
 assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , animated emojis many more small updates I will create a beautiful attracting readme file .

**Comment by Swarnendu0123** [comment]
Go fo it!

**Comment by Swarnendu0123** [comment]
Before I assign you you need to go through the rules and prerequisites: #24

**Comment by lassmara** [comment]
Please assign me this issue

**Comment by Swarnendu0123** [comment]
> Please assign me this issue
> 

Prerequisites #24

**Comment by Meetjain1** [comment]
@Swarnendu0123 2 days not completed yet !

**Comment by Meetjain1** [comment]
> @Meetjain1 First of all you should respect project admins and mentors. It's very inappropriate to ask that question! We already assigned you one issue. You first work on that and create a PR. You shouldn't claim 10 issues together.
> 
> @Sibam-Paul create another issue. I will assign you that!

Where I disrespect project admins and mentors tell me?
and why it is inappropriate ? didnt you have to give me the reason before unassigning me?
and also 
specify and provide me the links of the 10 issues raised by me if you are committed to your data.

**Comment by Swarnendu0123** [comment]
Sorry! I can't continue this conversation. I have informed the GSSoC Team, they will make decisions, what to do.

**Comment by Meetjain1** [comment]
> Sorry! I can't continue this conversation. I have informed the GSSoC Team, they will make decisions, what to do.

@Swarnendu0123 Thank-you for forwarding this issue to gssoc.
