### ISSUE TITLE
OOSI: Design the Links page for click matrics

### ISSUE THREAD

**Issue by krishna-singha** [oxiton-foundation/click-metrics#3]
# Current:

<img width="1710" alt="Screenshot 2024-05-13 at 11 29 31 PM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/162e1009-fb9f-4ff7-a955-8c529de3d970">

<br>

# Expected Results:

<img width="1710" alt="Screenshot 2024-05-13 at 11 56 31 PM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/794a8c2a-cc9f-4a3c-b66b-7bf7cbf6049b">

**Comment by bhaavvya** [comment]
Hello @Swarnendu0123 , can I try the frontend of the Links page.Can you please assign me this issue.

**Comment by Swarnendu0123** [comment]
Surely you can try!

But create the Pull Request for the task which is already assigned to you. Then you can move on to this.

**Comment by Swarnendu0123** [comment]
Oh sorry! you have already created the PR. I didn't notice. Go ahead with this issue.

**Comment by bhaavvya** [comment]
Hello @Swarnendu0123 , I have raised a new PR again , can you please review it.
