### ISSUE TITLE
GSSoC: Designing  the help page 

### ISSUE THREAD

**Issue by ManpreetSingh18** [oxiton-foundation/click-metrics#31]
On the Help page, we can have a form where user can write their query and emails and the admin can later respond to it. Something like the below image uploaded. 
![Screenshot 2024-05-28 003441](https://github.com/oxiton-foundation/click-metrics/assets/72294811/42547f04-d63a-45b9-adcb-ea3bbcb6d966)
![Screenshot 2024-05-28 003946](https://github.com/oxiton-foundation/click-metrics/assets/72294811/4fc33ee8-967e-4b2d-b03c-9d24e10c9ea7)

**Comment by Swarnendu0123** [comment]
Thanks for raising this!
- We are not accepting the dark theme, go with the light theme
- We don't need the picture. Go for simple UI.

**Comment by Swarnendu0123** [comment]
Fulfill the prerequisites first: #24

**Comment by ManpreetSingh18** [comment]
I have followed pages and make an account using github as mentioned in prerequite . I will go

**Comment by Anamikaghosh18** [comment]
I would like to contribute by designing the help page for our project. I would like to add some more features to the help page like if someone have any query they can fill the form and find the help . If you assign me this task , looking forward to your approval.

**Comment by Swarnendu0123** [comment]
Hello @Anamikaghosh18, @ManpreetSingh18 already claimed it. It is not inappropriate to claim someone's issue. Find out a new issue, there are many areas we need to work on.

**Comment by Swarnendu0123** [comment]
Just design the UI first and create a PR.
