### ISSUE TITLE
[Feature]Addition of qr code generator

### ISSUE THREAD

**Issue by litesh1123** [oxiton-foundation/click-metrics#32]
>Python libraries can be used to generate more efficient qr codes from urls.
>it will take short url as input or any other text user gives Input and qr code will be generated

**Comment by Swarnendu0123** [comment]
We are not using python! We want to continue it with js.

**Comment by litesh1123** [comment]
@Swarnendu0123 if u want to continue in js I can use kjua , qrcode.js

**Comment by Swarnendu0123** [comment]
Raise another issue and explain everything what you are going to do if I assign this to you.

**Comment by litesh1123** [comment]
OK I will raise issue by Tom morning
