### ISSUE TITLE
GSSoC: Designing the "Unlock Premium" page

### ISSUE THREAD

**Issue by Sumkaur02** [oxiton-foundation/click-metrics#33]
I can create an unlockable Premium Page to showcase a variety of plans with different pricing models, similar to the example below.
![Screenshot 2024-05-28 011959](https://github.com/oxiton-foundation/click-metrics/assets/144603204/0e31c2e4-8cf0-450e-a32d-95e1ce29f8f9)

**Comment by Swarnendu0123** [comment]
The project is open source, our target is to deliver the product for free. We don't need this page.
