### ISSUE TITLE
GSSoC : Adding Footer 

### ISSUE THREAD

**Issue by Sumkaur02** [oxiton-foundation/click-metrics#34]
I can add the footer to the website.
![Screenshot 2024-05-28 020154](https://github.com/oxiton-foundation/click-metrics/assets/144603204/bd4d0738-76ca-414e-b5e6-69d933b76578)

**Comment by Swarnendu0123** [comment]
Fulfill the prerequisites #24 to get the issue assigned.

**Comment by lassmara** [comment]
please assign me this issue

**Comment by Swarnendu0123** [comment]
> please assign me this issue
> 

Prerequisites #24

**Comment by Varsani2520** [comment]
Hey @Swarnendu0123 ,
i would like to work with you ,i can create footer for click-metrics web :
![image](https://github.com/oxiton-foundation/click-metrics/assets/137641079/e51cfb5b-0092-45e6-a7dd-963acab7ff1d)

**Comment by dhruv8433** [comment]
@Swarnendu0123 

i would like to work on this issue 
i can redesign footer something 

![image](https://github.com/oxiton-foundation/click-metrics/assets/114583978/50a29b35-ccc5-42f3-ae2c-fc6d278b01d7)

**Comment by Sumkaur02** [comment]
> Fulfill the prerequisites #24 to get the issue assigned.

Done

**Comment by yash28goyal** [comment]
I am interesting to contibute to this project so please assign this issue to me.

**Comment by Swarnendu0123** [comment]
Don't ask randomly assigning the issues, There are some steps mentioned in #24, which you need to fulfill before claiming any issue.

**Comment by yash28goyal** [comment]
> Don't ask randomly assigning the issues, There are some steps mentioned in #24, which you need to fulfill before claiming any issue.
I have done all the steps

**Comment by Swarnendu0123** [comment]
This issue is already assigned claim a new one!

**Comment by Sumkaur02** [comment]
@Swarnendu0123 The repository after forking already has a footer in it and it was not there before when you assigned this issue to me.
