### ISSUE TITLE
GSSoC: Feature Request - Generate QR Codes for Shortened URLs

### ISSUE THREAD

**Issue by himanshuraimau** [oxiton-foundation/click-metrics#35]
### Description

I would like to request a feature to generate and download QR codes for each shortened URL within our React application. This feature will facilitate offline sharing and enhance the overall user experience.

### Proposed Solution

- Use a QR code generation library such as `qrcode.react` to create QR codes.
- Integrate this functionality into the existing URL shortening flow.
- Provide a button or link to download the QR code as an image file (e.g., PNG).

### Screenshots

![image](https://github.com/oxiton-foundation/click-metrics/assets/134522022/42cb00a9-fe01-418b-aa6a-8c0ae2f63a70)

---

### Request for Assignment

Hi @Swarnendu0123,

I would like to work on this feature as part of GSSoC. Could you please assign this issue to me?

---

### Checklist

- [x] Signed up at [Oxiton Live](https://www.oxiton.live/)
- [x] Followed [Oxiton Foundation on GitHub](https://github.com/oxiton-foundation)
- [x] Followed [Oxiton Foundation on LinkedIn](https://www.linkedin.com/company/oxiton-foundation)
- [x] Followed [Oxiton Foundation on Instagram](https://www.instagram.com/oxitonfoundation/)
- [ ] Followed [Oxiton Foundation on Facebook](https://www.facebook.com/people/Oxiton-Foundation/61559802086402/) *(I don't have an account there)*
- [x] Followed [Oxiton Foundation on Dev.to](https://dev.to/oxiton_foundation)
- [x] Joined the [Discord community](https://discord.gg/DVWNcTqD)

Thank you!

**Comment by Swarnendu0123** [comment]
Go for it.

**Comment by Swarnendu0123** [comment]
Are you going to generate the qr in the front-end or backend?

**Comment by himanshuraimau** [comment]
> Are you going to generate the qr in the front-end or backend?

Since the backend part is not ready yet, I will generate the QR codes directly in the user's browser using client-side JavaScript. Alternatively, I can also work on establishing the backend part of the app.

**Comment by Swarnendu0123** [comment]
Go ahead!

**Comment by himanshuraimau** [comment]
Thank you for accepting the PR. Has anyone set up the backend of this project? If not, I can start working on that.

**Comment by Swarnendu0123** [comment]
> Thank you for accepting the PR. Has anyone set up the backend of this project? If not, I can start working on that.

We have not setup the backend now. You can go for backend setup!
