### ISSUE TITLE
GSSoC: Modify navbar

### ISSUE THREAD

**Issue by root-0101** [oxiton-foundation/click-metrics#36]
- It would be better if we make the navbar sticky as it is easier to navigate for the user and enhance the user experience, As on scrolling the navbar hides.

![Screenshot 2024-05-28 120316](https://github.com/oxiton-foundation/click-metrics/assets/142779809/1bcba949-6031-4ef9-b3fe-35cc9eef8d27)

![Screenshot 2024-05-28 120300](https://github.com/oxiton-foundation/click-metrics/assets/142779809/808caef9-405e-4140-b1fc-882aa6407042)

**Comment by Swarnendu0123** [comment]
Explain with screenshots.

**Comment by root-0101** [comment]
I have followed all the instruction mentioned in #24, Please assign me this issue and also attach the screenshot
