### ISSUE TITLE
GSSoC: Modify the buttons

### ISSUE THREAD

**Issue by root-0101** [oxiton-foundation/click-metrics#38]
- As now the hover effect makes the button fade which is not great as per the perspective of the user. so, it would be better to improve the hover effect of the buttons.

![Screenshot 2024-05-28 023006](https://github.com/oxiton-foundation/click-metrics/assets/142779809/8b9f00d6-f5cd-470d-9fa5-4e0e5bca735c)

![Screenshot 2024-05-28 022528](https://github.com/oxiton-foundation/click-metrics/assets/142779809/60aade45-937b-4d1d-8b13-7d8e4db78f58)

**Comment by Swarnendu0123** [comment]
We haven't designed the button, we are using the default theme.

Go through #24 before opening any issue.

**Comment by root-0101** [comment]
I have followed all the instruction mentioned in #24, Please assign me this issue

**Comment by Swarnendu0123** [comment]
We have already assigned one issue to you, please fulfill that before claiming another.

**Comment by root-0101** [comment]
ok, I understand I will soon raise my PR with the required changes

**Comment by Sibam-Paul** [comment]
@Swarnendu0123 Can I work on this issue as it is open??

**Comment by Hanshika248** [comment]
Please assign me the issue. I want to  solve the issue .
