### ISSUE TITLE
GSSoC: Link home page with the logo

### ISSUE THREAD

**Issue by root-0101** [oxiton-foundation/click-metrics#39]
- As nowadays all applications have link to the home/main page attached with the logo of their web/apps. So, it would be better to add link the home/main page with the logo

![Screenshot 2024-05-28 023729](https://github.com/oxiton-foundation/click-metrics/assets/142779809/2c9f8485-2d33-4f9c-aba4-f7ddbcc99e65)

**Comment by anuragnegi000** [comment]
I would like to work on this issue

**Comment by Swarnendu0123** [comment]
Welcome @anuragnegi000 and @root-0101,
Whoever meets the prerequisites #24 first, can claim the issue.

**Comment by root-0101** [comment]
I have completed all the prerequisites mentioned in #24, Please assign me this issue

**Comment by Iisha10** [comment]
I would like to work under this issue sir

**Comment by krishna-singha** [comment]
@Iisha10 Thank you for your interest in contributing! The issue you are referring to has already been addressed and merged into the project. Please find a new issue to work on and also go through #24
