### ISSUE TITLE
GSSOC: Home and Link page are not responsive in design

### ISSUE THREAD

**Issue by Maheshwari-Love** [oxiton-foundation/click-metrics#44]
The Home and links page are not designed responsive , refer to below screenshots

![image](https://github.com/oxiton-foundation/click-metrics/assets/142833275/1937a8b0-fb3a-4808-bdc0-2b01398aad4b)

![image](https://github.com/oxiton-foundation/click-metrics/assets/142833275/66c584c3-cdca-42fd-b4a9-3f4bb5aa3cbe)

I can fix this today itself,

**Comment by Maheshwari-Love** [comment]
@Swarnendu0123 can you please assign this issue to me, and please add the required labels

**Comment by Swarnendu0123** [comment]
Prerequisites: #24

**Comment by Maheshwari-Love** [comment]
done the steps for the Prerequisites: #24

**Comment by Maheshwari-Love** [comment]
@Swarnendu0123 Kindlly add the Labels on the PR and review it

**Comment by Maheshwari-Love** [comment]
@Swarnendu0123 Can i discuss what content actually you want to in the following pages
Link in bio
Campaign
And custom links
I mean any prototype?

**Comment by Swarnendu0123** [comment]
Yeah there is already some prototype available. Please look around the old issues.

**Comment by Swarnendu0123** [comment]
Signup to https://www.oxiton.live/contribute to see your points
