### ISSUE TITLE
GSSoC: Enhancing the visibility and usability of links page

### ISSUE THREAD

**Issue by ChethanaPotukanam** [oxiton-foundation/click-metrics#45]
The current links page is not looking proper . I want to make it more organised and responsive.

**Comment by Swarnendu0123** [comment]
Be specific, what you want to change.

> I want to make it more organised

Couldn't understand what you mean by `organised`. Don't tag maintainers in the issues.

**Comment by ChethanaPotukanam** [comment]
Apologizing for the mistake made.

I'd like to enhance the appearance of the links page by centering the content and enclosing it within a flexbox. This will create a more organised and visually appealing layout.

**Comment by Swarnendu0123** [comment]
This is a copy of issue #42. Closing it for now, feel free to raise another issue in other areas.
