### ISSUE TITLE
GSsoC: Shorten URLs is not working

### ISSUE THREAD

**Issue by GOKULGSECE** [oxiton-foundation/click-metrics#46]
Even if we are trying to generate the Shorten version of the URL it is not responding anything so i will fix the bug to respond in such a way that it can provide the shortest version of the URL
![Screenshot 2024-05-28 115906](https://github.com/oxiton-foundation/click-metrics/assets/125350820/3f18fa34-3c9f-4a44-9a8e-23ec7fd21f13)

**Comment by Swarnendu0123** [comment]
Discuss your approach clearly, and mention everything with a proper timeline and tech stack. Go through #24

**Comment by GOKULGSECE** [comment]
As i will solve the bug to provide a shortest version of the URL with the Tech stack as ReactJs as we no need of backend in this cause using a component i will be creating a shortest version of the URL and i have completed the #24 process

**Comment by Swarnendu0123** [comment]
What will be the domain of the generated URL?
Backend URL or Frontend URL?

**Comment by GOKULGSECE** [comment]
The domain will be backend

**Comment by GOKULGSECE** [comment]
The domain will be backend and it would be display via passing the data from the backend

**Comment by Swarnendu0123** [comment]
So you have to make the server from scratch. Are you ready to do that?

**Comment by GOKULGSECE** [comment]
You mean the backend of the entire website

**Comment by GOKULGSECE** [comment]
Oke I will do @Swarnendu0123

**Comment by GOKULGSECE** [comment]
@Swarnendu0123 I have a doubt whether the shortened URL is alone enough or we need to create such that when we click that link we need to redirect to that link please clear me thiss

**Comment by Swarnendu0123** [comment]
We just need to redirect it.

**Comment by GOKULGSECE** [comment]
@Swarnendu0123  ok got it

**Comment by GOKULGSECE** [comment]
@Swarnendu0123 can you provide me time till Monday as I have my sem exams going is that fine for you

**Comment by Gokul-3553** [comment]
@Swarnendu0123 i have raised the PR for the Assigned Issue please check through it and frontend is not at all working properly as everyone is just trying to make it attractive but it is not responsive in regrad to that i have added the link.tsx page where i have altered depending upon my Server(Backend) code please check through and make it responsive Thank You For this chance to improve my knowledge

**Comment by GOKULGSECE** [comment]
@Swarnendu0123 Sir actually due to the changes in the ui the code has jumped to 6000+lines so after fetching it I will try to change it can I give one more shot for implementation of backend

**Comment by Swarnendu0123** [comment]
Feel free to raise another.

**Comment by GOKULGSECE** [comment]
@Swarnendu0123 whether should I raise an issue or a PR

**Comment by GOKULGSECE** [comment]
@Swarnendu0123 oke I will request for another one

**Comment by Swarnendu0123** [comment]
Please discuss your changes on the specific PR that you have created. Don't write here and there. Does this issue have any relation with that PR? No right. Then why are you writing this here, 

Secondary, you have mentioned me in every comment. Don't do that, it doesn't look good. You have commented, we will see according to our timings. You don't need to tag maintainers aggressively.
