### ISSUE TITLE
GSSoC: Need a loader in whole website

### ISSUE THREAD

**Issue by Ansh101112** [oxiton-foundation/click-metrics#49]
Need a loader when the components are in rendering state that increase the overall ui and ux experience of user as well. I am a gssoc'24 contributor please assign me this issue and I want to work on this issue.

**Comment by Swarnendu0123** [comment]
Prerequisites: #24

**Comment by Ansh101112** [comment]
> Prerequisites: #24

Assign me

**Comment by Ansh101112** [comment]
done

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Swarnendu0123

**Comment by Maheshwari-Love** [comment]
@Swarnendu0123 can you please assign me this task
