### ISSUE TITLE
GSSoC: Profile button animations

### ISSUE THREAD

**Issue by anisharma07** [oxiton-foundation/click-metrics#52]
https://github.com/oxiton-foundation/click-metrics/assets/126901961/d7dc4f74-c8a0-4bce-a86a-38d4d241025f

The hover effect in profile buttons animation is just a normal text-underline .. I want to add animations to it like sliding line under text on hover with a nice  transition... I have gone through the steps in #24 

please assign the issue to me under gssoc'24

**Comment by krishna-singha** [comment]
Ok go for it.
