### ISSUE TITLE
GSSoC: fix sidebar position

### ISSUE THREAD

**Issue by root-0101** [oxiton-foundation/click-metrics#54]
- As on scrolling the sidebar also moves with the page. So, making the position of the sidebar fixed would be great 

https://github.com/oxiton-foundation/click-metrics/assets/142779809/1767e967-3ccc-43f4-b264-515332cae032

**Comment by Swarnendu0123** [comment]
Don't Create multiple issues. You can fix it on #50 Right? Push on the same branch. These are just <10 lines of changes. I will accept only one PR for both.

**Comment by DevGajjar28** [comment]
@Swarnendu0123 can you assign me?

**Comment by Swarnendu0123** [comment]
IG if @root-0101 is not working on it @DevGajjar28 can work. Wait for the message from @root-0101 before starting.

**Comment by root-0101** [comment]
- I have done the required changes, Please check the PR #93

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Swarnendu0123
