### ISSUE TITLE
Upgrade button does not working

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [oxiton-foundation/click-metrics#56]
Upgrade button does not working

**Comment by RamakrushnaBiswal** [comment]
assign me under GSSOC 24

**Comment by Swarnendu0123** [comment]
Explain what you want to do clearly.

**Comment by RamakrushnaBiswal** [comment]
When user click upon it pop up 3 cards or redirect a new page according to you .i can create some cards and add some prices and benefits here,so it's helpful for user to upgrade your service.

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 ??

**Comment by Swarnendu0123** [comment]
We are designing a free software. We don't need this feature.
