### ISSUE TITLE
GSSoC: Auto Commenting Feat for Issues and PRs

### ISSUE THREAD

**Issue by Asymtode712** [oxiton-foundation/click-metrics#57]
This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues and PRs as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![issue creation](https://github.com/oxiton-foundation/click-metrics/assets/115717746/9e7496b8-d17e-44a0-8e58-d256c86a5794)

**Comment by Asymtode712** [comment]
@Swarnendu0123 please assign me  this issue under gssoc

**Comment by Swarnendu0123** [comment]
Include #24 as rules in the comment.

**Comment by Swarnendu0123** [comment]
@Asymtode712 give me the comments you are going to attach for issues and PRs.

**Comment by Swarnendu0123** [comment]
I have modified the comments (included#24). Use the modified comments.

**Comment by Asymtode712** [comment]
@Swarnendu0123 Sure

**Comment by Swarnendu0123** [comment]
Can you automate one CI/CD which will check the pushed code is fine to merge or not?

**Comment by Asymtode712** [comment]
@Swarnendu0123 Sure, should I open an issue for it?

**Comment by Swarnendu0123** [comment]
Yes!
