### ISSUE TITLE
[Feat]: Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [oxiton-foundation/click-metrics#58]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![PR raised](https://github.com/oxiton-foundation/click-metrics/assets/115717746/b6be74fb-70a6-4b13-90bb-055578475d75)

**Comment by Asymtode712** [comment]
@Swarnendu0123 please assign me this issue under gssoc

**Comment by Swarnendu0123** [comment]
Merging it with #57
