### ISSUE TITLE
GSSoC: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [oxiton-foundation/click-metrics#59]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

![PR merged](https://github.com/oxiton-foundation/click-metrics/assets/115717746/1e94cb60-5766-4329-80c8-23a8214a5d39)

**Comment by Asymtode712** [comment]
@Swarnendu0123 please assign me this issue under gssoc

**Comment by Swarnendu0123** [comment]
Prerequisites: #24

**Comment by Asymtode712** [comment]
@Swarnendu0123 as this is a single automation issue u can remove level2 and change it to level1
