### ISSUE TITLE
[Feat]: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [oxiton-foundation/click-metrics#60]
This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

![Close Old Iss](https://github.com/oxiton-foundation/click-metrics/assets/115717746/a1f45d65-23d1-4cd4-8482-1294b75334b3)

**Comment by Asymtode712** [comment]
@Swarnendu0123 please assign me this issue under gssoc

**Comment by Swarnendu0123** [comment]
We don't need this.
