### ISSUE TITLE
GSSoC: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [oxiton-foundation/click-metrics#62]
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

![issue closed](https://github.com/oxiton-foundation/click-metrics/assets/115717746/5331a0c9-3e91-45aa-973f-6b82c005f3c8)

**Comment by Asymtode712** [comment]
@Swarnendu0123 please assign me this issue under gssoc

**Comment by Swarnendu0123** [comment]
Fulfill the prerequisites #24
