### ISSUE TITLE
OSSI: Making entire Page for Create New

### ISSUE THREAD

**Issue by bhaavvya** [oxiton-foundation/click-metrics#63]
Descriptions:
Create New button has no action as of now. I want to direct that page whenever Create New button is clicked.
![image](https://github.com/oxiton-foundation/click-metrics/assets/110487270/6c4c3886-c568-443f-ab14-23673e1ba247)

According to me, I will add cards having buttons which will redirect to links,qr-code page,etc. Other than this please suggest me other content to add in it.

**Comment by Swarnendu0123** [comment]
Just redirect to the links page.
