### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by bhaavvya** [oxiton-foundation/click-metrics#65]
Hey @Swarnendu0123, My 2 PRs were merged but it does not show any points.
![Screenshot 2024-05-28 185431](https://github.com/oxiton-foundation/click-metrics/assets/110487270/95bcbcde-3411-4f17-85fd-ca348e7afec3)

**Comment by Swarnendu0123** [comment]
Keep refreshing the page it should be there. And ask your ossi doubts in discord.
