### ISSUE TITLE
GSSoC: Modify the style of cards 

### ISSUE THREAD

**Issue by Vanicoding27** [oxiton-foundation/click-metrics#66]
I want to modify the style of cards to enhance the overall look of the website.
Please assign me this task as I want to contribute in  GSSoC.

![1881122a-5db5-403d-a664-06f18762be63](https://github.com/oxiton-foundation/click-metrics/assets/165997406/e29e3dc2-5bcb-4777-9961-df43a441c22c)

**Comment by Swarnendu0123** [comment]
this is a copy of #44
