### ISSUE TITLE
 GSSoC: Setup Folder Structure and Basic Files for Backend using Node.js and Express

### ISSUE THREAD

**Issue by himanshuraimau** [oxiton-foundation/click-metrics#70]
**Description**:
This issue aims to set up the initial folder structure and basic files for the backend of our project using Node.js and Express. By establishing the foundation for the backend, we can lay the groundwork for implementing key functionalities such as URL shortening, QR code generation, and analytics tracking.

**Steps**:
1. Initialize the backend repository and project structure.
2. Create necessary directories such as `src`, `routes`, `controllers`, `models`, `middlewares`, etc.
3. Set up essential files including `server.js`, `package.json`, `.gitignore`, and any configuration files.
4. Install required dependencies such as `express`, `body-parser`, `cors`, etc.
5. Implement a basic server setup in `server.js` to listen for incoming requests.
6. Configure routing for different endpoints in the `routes` directory.
7. Create placeholder controller functions in the `controllers` directory.
8. Set up basic error handling and middleware functions if necessary.

**Assignment**:
Please assign this issue to me. I will work on setting up the folder structure and basic files for the backend using Node.js and Express.

**Comment by Swarnendu0123** [comment]
Go for it! Chenge the documentation part also accordingly.

**Comment by himanshuraimau** [comment]
Ok

**Comment by himanshuraimau** [comment]
hey this issue is already completed can you close this issue.
