### ISSUE TITLE
 GSSoC: Create Express Server for handling functionalities of the the application using Mongodb

### ISSUE THREAD

**Issue by dfordp** [oxiton-foundation/click-metrics#76]
- Bootstrapping Express app & connecting with MongoDB atlas instance
- Creating relevant fields and tables with well defined routes and tables
- Connecting it with front end
- Implementing Password Based Authentication & creating Custom Authentication flow

**Comment by anuragnegi000** [comment]
Assign me this issue under GSSoC'24

**Comment by GitSentinel** [comment]
@anuragnegi000 The issue has been assigned to you. Refer to #24 and complete the work accordingly. Best of luck!

**Comment by dfordp** [comment]
Bro I asked to raise the issue first shouldn't in be assigned this?

**Comment by anuragnegi000** [comment]
@GitSentinel Okay thanks

**Comment by anuragnegi000** [comment]
The things that i'll be covering under this issue is:-
basic restful api ( signup, signin under the connection with mongoDB) for now,  if you guys want me to add something else please give suggestions below

**Comment by GitSentinel** [comment]
> Bro I asked to raise the issue first shouldn't I in be assigned this?

@dfordp Sorry for the mistake on my part. Since I have already assigned the issue to @anuragnegi000 , so re-assigning it to you and removing him from it will be hard. A sincere apology for my side.

**Comment by GitSentinel** [comment]
> The things that i'll be covering under this issue is:- basic restful api ( signup, signin under the connection with mongoDB) for now, if you guys want me to add something else please give suggestions below

Yes, that is the basic functions required. The other things required are:
- Implementing Password Based Authentication & creating Custom Authentication flow
- Bootstrapping Express app & connecting with MongoDB atlas instance
- Creating relevant fields and tables with well defined routes and tables
- Connecting it with front end

**Comment by anuragnegi000** [comment]
sure @GitSentinel

**Comment by Swarnendu0123** [comment]
@anuragnegi000 are you working on it?

**Comment by nishant0708** [comment]
Hey Is anyone Working On This Issue?? Can I work On this?

**Comment by anuragnegi000** [comment]
@Swarnendu0123 yes working need few more days as exams are going on

**Comment by lazybug19** [comment]
Is anyone working on this? @Swarnendu0123

**Comment by Swarnendu0123** [comment]
This is already done!
