### ISSUE TITLE
GSSoC: Add an Introduction to the site at home page

### ISSUE THREAD

**Issue by 18Venus** [oxiton-foundation/click-metrics#84]
We can utilize the empty space in the home page by giving short information about what is this site for and how is it beneficial. We can have a nice use of fonts and colors to make it appealing and have the links below it.

# Now
![matrixhomepage](https://github.com/oxiton-foundation/click-metrics/assets/149051659/7c211675-15d5-4205-8ece-b2afe347107b)

# Expected
![Screenshot (237)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/b02dc07f-40c7-43e5-83de-f8b191114f4b)

- add one announcement banner. 

As we can see there is a lot of white space.

**Comment by Swarnendu0123** [comment]
Sign up to https://www.oxiton.live/auth

**Comment by 18Venus** [comment]
hey @Swarnendu0123 I'm sorry but can you guide me a bit? I have started both the frontend and backend. But not able to access the site after this page.  Sorry and thank you!

https://github.com/oxiton-foundation/click-metrics/assets/149051659/486846b8-539c-4e19-a133-7499e6474ec1

**Comment by Swarnendu0123** [comment]
Please set up our new codes, we have removed this unstructured landing page.

**Comment by 18Venus** [comment]
@Swarnendu0123 sure thank you!
