### ISSUE TITLE
[Bug]: Issue in autocommenting on merged pr

### ISSUE THREAD

**Issue by Anshika14528** [oxiton-foundation/click-metrics#88]
I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message
<img width="1436" alt="Screenshot 2024-05-30 at 5 41 21 PM" src="https://github.com/oxiton-foundation/click-metrics/assets/168436423/7d13556b-d875-4e62-b9a6-98f06f06c9f4">

Please let me work on this

**Comment by Swarnendu0123** [comment]
@GitSentinel What is your views on it?

**Comment by GitSentinel** [comment]
According to me at this point, this should not pose any problem to us and is not of high priority.. We can assign it as Level 1. It will come into picture when we merge PRs and the site crashes.

**Comment by Swarnendu0123** [comment]
Thanks @GitSentinel for your suggestion.
