### ISSUE TITLE
GSSoC: Vercel Deployment Error

### ISSUE THREAD

**Issue by Swarnendu0123** [oxiton-foundation/click-metrics#95]
![Screenshot (238)](https://github.com/oxiton-foundation/click-metrics/assets/94161758/421c864d-e12a-423f-aa77-799e5cfa7928)

We are getting some deployment errors. Fix the errors.

**Comment by Swarnendu0123** [comment]
[StephenStolk](https://github.com/StephenStolk) Please Resolve this! Create another PR.

**Comment by anuragnegi000** [comment]
i would like to give it a shot, assign this to me under GSSoC'24

**Comment by Rohanshu-33** [comment]
I can give a try. I have used Vercel many a times and I am pretty sure on solving this issue. Kindly assign this to me under GSSoC'24

**Comment by Hemu21** [comment]
@Swarnendu0123  can you please assign this to me.
