### ISSUE TITLE
Need to change the home page

### ISSUE THREAD

**Issue by Ansh101112** [oxiton-foundation/click-metrics#99]
### Issue Description: 
It needs to change the home page as it needs to showcase more sections like stats of the website and more content about the website.

I am a GSSOC'24 contributor and want to work on this issue please assign me this issue for working on this issue.

**Comment by GitSentinel** [comment]
@Ansh101112 Send me the Figma design here before.

**Comment by Ansh101112** [comment]
can i showcase the changes on directly code and add screenshots here?

**Comment by Ansh101112** [comment]
> @Ansh101112 Send me the Figma design here before.

Here are some sections designs that i want to add in the home page with content and image in the website. @GitSentinel @Swarnendu0123 

![Screenshot (160)](https://github.com/oxiton-foundation/click-metrics/assets/87803348/2ff834e1-01d9-433d-ae83-e35b5caf122b)
![Screenshot (161)](https://github.com/oxiton-foundation/click-metrics/assets/87803348/3181a084-d333-4062-9e5d-835e11af1b16)

**Comment by Swarnendu0123** [comment]
Add it in light mode.

**Comment by Ansh101112** [comment]
> Add it in light mode.

Okay sure sir
